version: "3"

services:
  migrations:
    build:
      target: full
    image: mediacms/mediacms-dev:full
    pull_policy: never

  web:
    image: mediacms/mediacms-dev:full
    pull_policy: never
    environment:
      USE_WHISPER_TRANSCRIBE: 'True'
      WHISPER_MODEL: 'medium'
      WHISPER_BIN: '/home/mediacms.io/bin/whisper'
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY:-}
      APPROVAL_REVIEWER: ${APPROVAL_REVIEWER:-admin}
      IP_WHITELIST: ${IP_WHITELIST:-}

  celery_worker:
    image: mediacms/mediacms-dev:full
    pull_policy: never
    environment:
      USE_WHISPER_TRANSCRIBE: 'True'
      WHISPER_MODEL: 'medium'
      WHISPER_BIN: '/home/mediacms.io/bin/whisper'
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY:-}
      APPROVAL_REVIEWER: ${APPROVAL_REVIEWER:-admin}
      IP_WHITELIST: ${IP_WHITELIST:-}
