version: "3"

services:
  migrations:
    build:
      target: full
    image: mediacms/mediacms-dev:full
    pull_policy: never

  web:
    image: mediacms/mediacms-dev:full
    pull_policy: never
    environment:
      USE_VIDEOCAPTIONER_TRANSCRIBE: 'True'
      VIDEOCAPTIONER_COMMAND: 'videocaptioner'
      VIDEOCAPTIONER_ASR: 'bijian'
      VIDEOCAPTIONER_LANGUAGE: 'auto'
      VIDEOCAPTIONER_SUBTITLE_LANGUAGE_CODE: 'zh-Hans'
      VIDEOCAPTIONER_SUBTITLE_LANGUAGE_TITLE: '简体中文'

  celery_worker:
    image: mediacms/mediacms-dev:full
    pull_policy: never
    environment:
      USE_VIDEOCAPTIONER_TRANSCRIBE: 'True'
      VIDEOCAPTIONER_COMMAND: 'videocaptioner'
      VIDEOCAPTIONER_ASR: 'bijian'
      VIDEOCAPTIONER_LANGUAGE: 'auto'
      VIDEOCAPTIONER_SUBTITLE_LANGUAGE_CODE: 'zh-Hans'
      VIDEOCAPTIONER_SUBTITLE_LANGUAGE_TITLE: '简体中文'
