version: "3"

services:
  web:
    environment:
      AUTO_WHISPER_TRANSCRIBE_ON_UPLOAD: ${AUTO_WHISPER_TRANSCRIBE_ON_UPLOAD:-False}
      USE_VIDEOCAPTIONER_TRANSCRIBE: ${USE_VIDEOCAPTIONER_TRANSCRIBE:-True}
      VIDEOCAPTIONER_COMMAND: ${VIDEOCAPTIONER_COMMAND:-videocaptioner}
      VIDEOCAPTIONER_ASR: ${VIDEOCAPTIONER_ASR:-bijian}
      VIDEOCAPTIONER_LANGUAGE: ${VIDEOCAPTIONER_LANGUAGE:-auto}
      VIDEOCAPTIONER_SUBTITLE_LANGUAGE_CODE: ${VIDEOCAPTIONER_SUBTITLE_LANGUAGE_CODE:-zh-Hans}
      VIDEOCAPTIONER_SUBTITLE_LANGUAGE_TITLE: ${VIDEOCAPTIONER_SUBTITLE_LANGUAGE_TITLE:-简体中文}

  celery_worker:
    image: mediacms/mediacms:full
    environment:
      AUTO_WHISPER_TRANSCRIBE_ON_UPLOAD: ${AUTO_WHISPER_TRANSCRIBE_ON_UPLOAD:-False}
      USE_VIDEOCAPTIONER_TRANSCRIBE: ${USE_VIDEOCAPTIONER_TRANSCRIBE:-True}
      VIDEOCAPTIONER_COMMAND: ${VIDEOCAPTIONER_COMMAND:-videocaptioner}
      VIDEOCAPTIONER_ASR: ${VIDEOCAPTIONER_ASR:-bijian}
      VIDEOCAPTIONER_LANGUAGE: ${VIDEOCAPTIONER_LANGUAGE:-auto}
      VIDEOCAPTIONER_SUBTITLE_LANGUAGE_CODE: ${VIDEOCAPTIONER_SUBTITLE_LANGUAGE_CODE:-zh-Hans}
      VIDEOCAPTIONER_SUBTITLE_LANGUAGE_TITLE: ${VIDEOCAPTIONER_SUBTITLE_LANGUAGE_TITLE:-简体中文}
