# Generated by Django 5.2.6 on 2026-05-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_embedmediacourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCaptionerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('fail', 'Fail'), ('success', 'Success')], db_index=True, default='pending', max_length=20)),
                ('asr', models.CharField(default='bijian', max_length=50)),
                ('source_language', models.CharField(default='auto', max_length=20)),
                ('logs', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.language')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocaptioner_requests', to='files.media')),
            ],
            options={
                'verbose_name': 'VideoCaptioner Request',
                'verbose_name_plural': 'VideoCaptioner Requests',
                'ordering': ['-add_date'],
            },
        ),
    ]
