# Generated by Django 5.2.6 on 2026-05-17 13:02

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_embedmediacourse'),
        ('users', '0002_user_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Vector extension already created manually via sudo -u postgres
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchical classification tree', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='files.category'),
        ),
        migrations.AddField(
            model_name='media',
            name='ai_metadata',
            field=models.JSONField(blank=True, help_text='Type-specific AI metadata: document(page_count,author,keywords), image(resolution,colors,objects), video(keyframes,chapters), audio(speaker_count), etc.', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated content summary (separate from user-editable description)'),
        ),
        migrations.AddField(
            model_name='media',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='AI text embedding vector (1536-dim) for semantic similarity search', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='language',
            field=models.CharField(blank=True, help_text='Detected content language code, e.g. zh / en / ja', max_length=10),
        ),
        migrations.AddField(
            model_name='media',
            name='transcript_text',
            field=models.TextField(blank=True, help_text='AI speech-to-text full transcript with timestamps (JSON) for video/audio'),
        ),
        migrations.AddField(
            model_name='tag',
            name='confidence',
            field=models.FloatField(blank=True, help_text='AI confidence score 0-1, only for AI-generated tags', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='source',
            field=models.CharField(choices=[('ai', 'AI Auto-generated'), ('human', 'Human Created'), ('imported', 'Imported')], db_index=True, default='human', help_text='Whether tag was AI-generated, human-created, or imported', max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_reviewed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether media is reviewed, so it can appear on public listings'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image'), ('pdf', 'Pdf'), ('audio', 'Audio'), ('document', 'Document'), ('text', 'Text'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation')], db_index=True, default='video', max_length=20),
        ),
        migrations.AddIndex(
            model_name='media',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='media_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
