# Generated by Django 5.2.6 on 2026-05-18 05:06

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_category_parent_media_ai_metadata_media_ai_summary_and_more'),
        ('users', '0002_user_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='media',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='media_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
