# Generated by Django 5.2.6 on 2026-05-18 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_trigram_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique share token (UUID)', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('download', 'View + Download'), ('edit', 'View + Download + Edit Metadata')], default='view', max_length=20)),
                ('password', models.CharField(blank=True, help_text='Hashed password for access protection', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Link expiration time (null = never)', null=True)),
                ('max_views', models.IntegerField(blank=True, help_text='Max number of times link can be accessed (null = unlimited)', null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='files.media')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
