# Generated by Django 5.2.6 on 2026-05-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0023_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archived media hidden from listings'),
        ),
    ]
