# Generated by Django 5.2.6 on 2026-05-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0024_add_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_important',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Marked as important — triggers notification to all users',
            ),
        ),
    ]
