# Generated by Django 5.2.6 on 2026-06-01 09:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0025_add_is_important'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='media',
            name='media_embedding_idx',
        ),
        migrations.AlterField(
            model_name='media',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='AI text embedding vector (1024-dim) for semantic similarity search', null=True),
        ),
        migrations.AddIndex(
            model_name='media',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='media_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.CreateModel(
            name='MediaFaceEmbedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('source_type', models.CharField(choices=[('ai', 'AI'), ('human', 'Human'), ('imported', 'Imported')], db_index=True, default='ai', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('start_seconds', models.FloatField(blank=True, null=True)),
                ('end_seconds', models.FloatField(blank=True, null=True)),
                ('frame_no', models.IntegerField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('extra_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='files.media')),
            ],
            options={
                'ordering': ['media_id', 'start_seconds', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.IntegerField()),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('content', models.TextField()),
                ('content_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('source_type', models.CharField(choices=[('subtitle', 'Subtitle'), ('whisper', 'Whisper'), ('ai', 'AI'), ('imported', 'Imported')], db_index=True, default='subtitle', max_length=20)),
                ('extra_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.language')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='files.media')),
                ('subtitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='files.subtitle')),
            ],
            options={
                'ordering': ['media_id', 'segment_index', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafaceembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='mface_embed_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='mediafaceembedding',
            index=models.Index(fields=['media', 'start_seconds'], name='mface_media_start_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafaceembedding',
            index=models.Index(fields=['confidence'], name='mface_conf_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediafaceembedding',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='mface_conf_range'),
        ),
        migrations.AddConstraint(
            model_name='mediafaceembedding',
            constraint=models.CheckConstraint(condition=models.Q(('start_seconds__isnull', True), ('start_seconds__gte', 0), _connector='OR'), name='mface_start_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='mediafaceembedding',
            constraint=models.CheckConstraint(condition=models.Q(('end_seconds__isnull', True), ('start_seconds__isnull', True), ('end_seconds__gte', models.F('start_seconds')), _connector='OR'), name='mface_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='trseg_search_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['media', 'start_seconds'], name='trseg_media_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.UniqueConstraint(fields=('media', 'subtitle', 'segment_index'), name='trseg_media_sub_idx_uniq'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.CheckConstraint(condition=models.Q(('start_seconds__gte', 0)), name='trseg_start_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_seconds__gte', models.F('start_seconds'))), name='trseg_end_after_start'),
        ),
    ]
