# Generated by Django 5.2.6 on 2026-06-01 09:24

import django.contrib.postgres.indexes
import pgvector.django.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0026_mediafaceembedding_transcriptsegment_and_more'),
        ('users', '0003_notification_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image'), ('pdf', 'Pdf'), ('audio', 'Audio'), ('document', 'Document'), ('text', 'Text'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation')], db_index=True, default='video', max_length=20),
        ),
        migrations.AddIndex(
            model_name='media',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='media_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
