# Generated by Django 5.2.6 on 2026-06-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0027_category_parent_alter_media_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status', max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_reviewed',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether media is reviewed, so it can appear on public listings'),
        ),
    ]
