# Generated by Django 5.2.6 on 2026-06-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0029_ensure_waic_fixed_categories'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS files_videocaptionerrequest (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        add_date timestamp with time zone NOT NULL,
                        status varchar(20) NOT NULL,
                        asr varchar(50) NOT NULL,
                        source_language varchar(20) NOT NULL,
                        logs text NULL,
                        language_id integer NOT NULL REFERENCES files_language(id) DEFERRABLE INITIALLY DEFERRED,
                        media_id integer NOT NULL REFERENCES files_media(id) DEFERRABLE INITIALLY DEFERRED
                    );
                    CREATE INDEX IF NOT EXISTS files_videocaptionerrequest_status_33f03479 ON files_videocaptionerrequest (status);
                    CREATE INDEX IF NOT EXISTS files_videocaptionerrequest_language_id_7a7c0f6f ON files_videocaptionerrequest (language_id);
                    CREATE INDEX IF NOT EXISTS files_videocaptionerrequest_media_id_96bddbbd ON files_videocaptionerrequest (media_id);
                    """,
                    reverse_sql="DROP TABLE IF EXISTS files_videocaptionerrequest CASCADE;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='VideoCaptionerRequest',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('add_date', models.DateTimeField(auto_now_add=True)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('fail', 'Fail'), ('success', 'Success')], db_index=True, default='pending', max_length=20)),
                        ('asr', models.CharField(default='bijian', max_length=50)),
                        ('source_language', models.CharField(default='auto', max_length=20)),
                        ('logs', models.TextField(blank=True, null=True)),
                        ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.language')),
                        ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocaptioner_requests', to='files.media')),
                    ],
                    options={
                        'verbose_name': 'VideoCaptioner Request',
                        'verbose_name_plural': 'VideoCaptioner Requests',
                        'ordering': ['-add_date'],
                    },
                ),
            ],
        ),
    ]
