export const messages = {
  "app.loadingEditor": "正在加载编辑器...",
  "app.newProject": "新建项目",
  "app.newVerticalVideo": "新建竖屏视频",
  "app.newHorizontalVideo": "新建横屏视频",
  "app.newSquareVideo": "新建方形视频",
} as const;

const EXACT_TRANSLATIONS: Record<string, string> = {
  "Open Reel": "OpenReel",
  "Open Reel Video": "OpenReel 视频编辑器",
  "OpenReel": "OpenReel",
  "From idea to export.": "从灵感到成片。",
  "In your browser.": "就在浏览器中。",
  "Pick a format and start creating. You can change this anytime.": "选择一个格式立即开始创作，之后也可以随时调整。",
  "Vertical": "竖屏",
  "Horizontal": "横屏",
  "Square": "方形",
  "TikTok, Reels, Shorts": "TikTok、Reels、Shorts",
  "YouTube, Vimeo, Web": "YouTube、Vimeo、网页",
  "Instagram, Facebook": "Instagram、Facebook",
  "Start creating": "开始创作",
  "Browse templates": "浏览模板",
  "Recent projects": "最近项目",
  "Open editor": "打开编辑器",
  "Skip on startup": "启动时跳过",
  "Press": "按",
  "to skip": "可跳过",
  "Back": "返回",
  "Templates": "模板",
  "Recent Projects": "最近项目",
  "Loading recent projects...": "正在加载最近项目...",
  "No Recent Projects": "暂无最近项目",
  "Your recently opened projects will appear here. Start a new project or use a template to get started.": "你最近打开的项目会显示在这里。新建项目或使用模板即可开始。",
  "Remove from recent": "从最近项目中移除",
  "Recent projects are stored locally in your browser": "最近项目保存在你的浏览器本地",
  "Today": "今天",
  "Yesterday": "昨天",
  "Desktop Only": "仅支持桌面端",
  "OpenReel is a professional video editor that requires a desktop or laptop computer.": "OpenReel 是专业视频编辑器，需要在台式机或笔记本电脑上使用。",
  "Please visit this page on your desktop or laptop to start creating amazing videos.": "请使用台式机或笔记本电脑访问此页面，开始创作精彩视频。",
  "Learn More": "了解更多",
  "Loading video...": "正在加载视频...",
  "Video Not Found": "视频不存在",
  "This video doesn't exist or the link is invalid.": "该视频不存在，或分享链接无效。",
  "Create Your Own Video": "创建你自己的视频",
  "Link Expired": "链接已过期",
  "This share link has expired. Share links are only valid for 24 hours.": "该分享链接已过期。分享链接仅在 24 小时内有效。",
  "Error": "错误",
  "Something went wrong": "发生错误",
  "An unexpected error occurred": "发生了意外错误",
  "Try Again": "重试",
  "Shared Video": "分享的视频",
  "Your browser does not support the video tag.": "你的浏览器不支持视频播放。",
  "Download": "下载",
  "Create Your Own": "自己创建",
  "Made with": "由以下工具制作",
  "Settings": "设置",
  "General": "常规",
  "API Keys": "API 密钥",
  "Configure preferences and manage API keys for external services.": "配置偏好设置并管理外部服务的 API 密钥。",
  "Project Composition": "项目画布",
  "Set the canvas dimensions for your project. Pick a preset for TikTok, Reels, YouTube, or enter custom values.": "设置项目画布尺寸。可直接选择 TikTok、Reels、YouTube 预设，也可以输入自定义尺寸。",
  "16:9 Landscape (1080p)": "16:9 横屏（1080p）",
  "9:16 Vertical (TikTok/Reels)": "9:16 竖屏（TikTok/Reels）",
  "1:1 Square": "1:1 方形",
  "4:5 Portrait": "4:5 竖构图",
  "4:3 Standard": "4:3 标准",
  "21:9 Cinematic": "21:9 电影感",
  "4K Landscape": "4K 横屏",
  "Width": "宽度",
  "Height": "高度",
  "Apply": "应用",
  "Auto-Save": "自动保存",
  "Enable auto-save": "启用自动保存",
  "Automatically save your project at regular intervals": "按固定时间间隔自动保存项目",
  "Save every": "每隔",
  "1 minute": "1 分钟",
  "2 minutes": "2 分钟",
  "5 minutes": "5 分钟",
  "10 minutes": "10 分钟",
  "15 minutes": "15 分钟",
  "30 minutes": "30 分钟",
  "Default AI Providers": "默认 AI 服务",
  "Choose which service to use by default for AI features.": "选择 AI 功能默认使用的服务。",
  "Configure API keys in the \"API Keys\" tab first.": "请先在“API 密钥”标签页中配置对应的 API 密钥。",
  "Text to Speech/Voice To Speech/Sound Effects": "文本转语音 / 语音转语音 / 音效",
  "AI Assistant (LLM)": "AI 助手（LLM）",
  "AI Aggregator": "AI 聚合服务",
  "Video/image generation, upscaling, and creative AI tools": "用于视频/图像生成、超分辨率增强与创意 AI 工具。",
  "Piper (Free / Built-in)": "Piper（免费 / 内置）",
  "Secure API Key Storage": "安全 API 密钥存储",
  "Set up a master password to encrypt and store your API keys locally.": "设置主密码，在本地加密并保存你的 API 密钥。",
  "Keys are encrypted with AES-256-GCM and never leave your browser.": "密钥会使用 AES-256-GCM 加密，且不会离开你的浏览器。",
  "Set Up Master Password": "设置主密码",
  "Session Locked": "会话已锁定",
  "Enter your master password to view and manage API keys.": "请输入主密码以查看和管理 API 密钥。",
  "Unlock": "解锁",
  "Change Password": "修改密码",
  "Lock": "锁定",
  "Hide key": "隐藏密钥",
  "Show key": "显示密钥",
  "Delete key": "删除密钥",
  "Paste your API key here": "在此粘贴 API 密钥",
  "Cancel": "取消",
  "Save Key": "保存密钥",
  "Current Password": "当前密码",
  "Enter current password": "输入当前密码",
  "Password": "密码",
  "Master Password": "主密码",
  "Min. 8 characters": "至少 8 个字符",
  "Enter master password": "输入主密码",
  "New Password": "新密码",
  "Confirm Password": "确认密码",
  "Repeat password": "再次输入密码",
  "Confirm New Password": "确认新密码",
  "Repeat new password": "再次输入新密码",
  "Processing...": "处理中...",
  "Set Password": "设置密码",
  "Set Master Password": "设置主密码",
  "Unlock Settings": "解锁设置",
  "Change Master Password": "修改主密码",
  "Create a master password to encrypt your API keys. This password is never stored — only a verification hash is kept.": "创建主密码以加密 API 密钥。系统不会保存你的密码本身，只会保存校验哈希。",
  "Enter your master password to access encrypted API keys.": "输入主密码以访问已加密的 API 密钥。",
  "Change your master password. All stored keys will be re-encrypted.": "修改主密码后，所有已保存的密钥都会重新加密。",
  "Your password is used to derive an encryption key via PBKDF2 (100k iterations). API keys are encrypted with AES-256-GCM. If you forget this password, stored keys cannot be recovered.": "你的密码会通过 PBKDF2（10 万次迭代）派生出加密密钥。API 密钥使用 AES-256-GCM 加密。如果忘记该密码，已保存的密钥将无法恢复。",
  "Password must be at least 8 characters": "密码至少需要 8 个字符",
  "Passwords do not match": "两次输入的密码不一致",
  "New password must be at least 8 characters": "新密码至少需要 8 个字符",
  "New passwords do not match": "两次输入的新密码不一致",
  "Incorrect password": "密码错误",
  "Operation failed. Check your current password.": "操作失败，请检查当前密码是否正确。",
  "An error occurred": "发生错误",
  "Dismiss notification": "关闭通知",
  "Notifications": "通知",
  "Back to Home": "返回首页",
  "Search effects for selected clip...": "搜索当前选中片段的效果...",
  "Search tools, effects, or ask AI...": "搜索工具、效果，或向 AI 提问...",
  "Editor Tour": "编辑器导览",
  "Animation & Effects Tour": "动画与特效导览",
  "Press ? for shortcuts": "按 ? 查看快捷键",
  "Theme: light": "主题：浅色",
  "Theme: dark": "主题：深色",
  "Theme: system": "主题：跟随系统",
  "Settings & API Keys": "设置与 API 密钥",
  "Project JSON - Export/Import": "项目 JSON - 导出 / 导入",
  "Keyframe Editor": "关键帧编辑器",
  "Audio Mixer – track volume and master level": "音频混音器 - 轨道音量与主输出电平",
  "History - Undo/Redo": "历史记录 - 撤销 / 重做",
  "Record": "录制",
  "Screen Recording": "屏幕录制",
  "Downloaded!": "已下载！",
  "EXPORT": "导出",
  "Best Match": "最佳匹配",
  "Custom Export...": "自定义导出...",
  "Full settings with AI upscaling": "完整导出设置，支持 AI 超分辨率增强",
  "Action History": "操作历史",
  "Initializing...": "正在初始化...",
  "Complete!": "完成！",
  "Saved!": "已保存！",
  "Export failed": "导出失败",
  "Recording failed": "录制失败",
  "No video data was captured. Please try again.": "未捕获到视频数据，请重试。",
  "Failed to import screen recording": "导入屏幕录制失败",
  "Failed to import webcam recording": "导入摄像头录制失败",
  "Screen and webcam added to assets. Use the timeline to composite them.": "屏幕和摄像头素材已加入资源库，可在时间线中进行合成。",
  "Screen recording added to assets.": "屏幕录制已加入资源库。",
  "Import failed": "导入失败",
  "MP4 Standard": "MP4 标准",
  "4K Standard": "4K 标准",
  "1080p High Quality": "1080p 高质量",
  "1080p 60fps": "1080p 60fps",
  "Audio Only (WAV)": "仅音频（WAV）",
  "Web & social": "网页与社交媒体",
  "YouTube 4K": "YouTube 4K",
  "High bitrate": "高码率",
  "Smooth playback": "流畅播放",
  "Uncompressed audio": "无损音频",
  "Export Video": "导出视频",
  "Presets": "预设",
  "Custom": "自定义",
  "For Your Video": "适配当前视频",
  "Vertical (TikTok, Reels, Shorts)": "竖屏（TikTok、Reels、Shorts）",
  "Square (Instagram Feed)": "方形（Instagram 动态）",
  "Horizontal (YouTube, Twitter)": "横屏（YouTube、X/Twitter）",
  "Format": "格式",
  "Codec": "编码器",
  "Resolution": "分辨率",
  "Frame Rate": "帧率",
  "Bitrate (kbps)": "码率（kbps）",
  "Quality": "质量",
  "Smaller": "更小",
  "Better": "更好",
  "Audio Settings": "音频设置",
  "Enhance Quality (Upscaling)": "增强质量（超分辨率）",
  "Quality Mode": "质量模式",
  "fast": "快速",
  "balanced": "平衡",
  "quality": "高质量",
  "Fast": "快速",
  "Balanced": "平衡",
  "Enhance quality when exporting to higher resolutions than source. Uses edge-directed interpolation for sharper details.": "当导出分辨率高于源素材时启用质量增强，使用边缘导向插值让细节更清晰。",
  "Sharpening": "锐化",
  "None": "无",
  "Max": "最大",
  "Est. time:": "预计时间：",
  "Get accurate estimate": "获取更准确的预估",
  "Testing...": "测试中...",
  "CPU": "CPU",
  "GPU": "GPU",
  "Unknown": "未知",
  "HW Encode": "硬件编码",
  "Software only": "仅软件编码",
  "Codecs": "编码器",
  "Hardware accelerated": "硬件加速",
  "Start Export": "开始导出",
  "Media file": "媒体文件",
  "All": "全部",
  "Video": "视频",
  "Audio": "音频",
  "Text": "文字",
  "Animation": "动画",
  "Transform": "变换",
  "Position & Size": "位置与尺寸",
  "Position, scale, and rotate the clip": "调整片段的位置、缩放和旋转",
  "Crop": "裁剪",
  "Crop and frame the clip": "裁剪并调整片段画面",
  "Speed Control": "速度控制",
  "Time": "时间",
  "Control playback speed and time remapping": "控制播放速度和时间重映射",
  "Video Effects": "视频效果",
  "Brightness, contrast, saturation, blur, sharpen": "亮度、对比度、饱和度、模糊、锐化",
  "Color Grading": "调色",
  "Color wheels, curves, LUTs, and HSL adjustments": "色轮、曲线、LUT 和 HSL 调整",
  "Green Screen": "绿幕抠像",
  "Chroma key for green/blue screen removal": "用于移除绿幕 / 蓝幕的色度键控",
  "Background Removal": "背景移除",
  "AI-powered background removal": "AI 背景移除",
  "Masking": "遮罩",
  "Shape masks to reveal or hide areas": "使用形状遮罩显示或隐藏区域",
  "Motion Tracking": "运动跟踪",
  "Track motion and attach elements": "跟踪运动并附加元素",
  "Picture-in-Picture": "画中画",
  "Position clips as picture-in-picture overlays": "将片段作为画中画叠加显示",
  "Blend Mode": "混合模式",
  "Blend modes and opacity controls": "混合模式与透明度控制",
  "3D Transform": "3D 变换",
  "3D rotation and perspective effects": "3D 旋转与透视效果",
  "Keyframes": "关键帧",
  "Animate properties over time": "让属性随时间变化形成动画",
  "Transitions": "转场",
  "Clip-to-clip transitions": "片段与片段之间的转场",
  "Motion Presets": "运动预设",
  "Pre-built motion animations": "预置运动动画",
  "Audio Effects": "音频效果",
  "EQ, compressor, reverb, and more": "均衡器、压缩器、混响等",
  "Audio Ducking": "自动压低背景音",
  "Auto-duck music under voice": "检测人声并自动压低背景音乐",
  "Text Properties": "文字属性",
  "Font, size, color, and text styling": "字体、字号、颜色与文字样式",
  "Text Animation": "文字动画",
  "Animate text with presets": "使用预设为文字添加动画",
  "Shape Properties": "图形属性",
  "Shapes": "图形",
  "Shape fill, stroke, and effects": "图形填充、描边与效果",
  "Search all effects and tools...": "搜索全部效果和工具...",
  "No effects found": "未找到效果",
  "Try a different search term or category": "请尝试其他搜索词或分类",
  "↵ to select": "按回车选择",
  "↑↓ Navigate": "↑↓ 导航",
  "↵ Select": "↵ 选择",
  "ESC Close": "ESC 关闭",
  "Undo (Cmd+Z)": "撤销（Cmd+Z）",
  "Redo (Cmd+Shift+Z)": "重做（Cmd+Shift+Z）",
  "Split clip at playhead (S)": "在播放头处分割片段（S）",
  "SPLIT": "分割",
  "Delete clip (Del)": "删除片段（Del）",
  "Add new track": "添加新轨道",
  "Add Track": "添加轨道",
  "Video Track": "视频轨道",
  "Audio Track": "音频轨道",
  "Image Track": "图片轨道",
  "Text Track": "文字轨道",
  "Graphics Track": "图形轨道",
  "Manage track layers": "管理轨道层级",
  "LAYERS": "轨道层级",
  "Track Layers": "轨道层级",
  "No tracks yet": "暂无轨道",
  "Move up": "上移",
  "Move down": "下移",
  "Disable snapping": "关闭吸附",
  "Enable snapping": "启用吸附",
  "SNAP": "吸附",
  "Large tracks": "大轨道",
  "Small tracks": "小轨道",
  "Zoom out": "缩小",
  "Zoom in": "放大",
  "Maximize timeline": "最大化时间线",
  "Retry": "重试",
  "just now": "刚刚",
  "Current Project": "当前项目",
  "Rename project": "重命名项目",
  "New Project": "新建项目",
  "Start fresh with a new canvas": "从空白画布开始创建",
  "Recover Your Work": "恢复你的工作",
  "We found an unsaved project": "我们发现了一个未保存的项目",
  "Last saved": "最近保存于",
  "Start Fresh": "重新开始",
  "Recovering...": "恢复中...",
  "Recover Project": "恢复项目",
  "Clear all saved projects": "清除所有已保存项目",
  "Loading templates...": "正在加载模板...",
  "Search templates...": "搜索模板...",
  "No templates found": "未找到模板",
  "Try adjusting your search or filter": "请尝试调整搜索词或筛选条件",
  "Preset": "预设方案",
  "Reset All": "全部重置",
  "Search shortcuts...": "搜索快捷键...",
  "Keyboard Shortcuts": "快捷键",
  "Enabled": "已启用",
  "Scenes": "场景",
  "Customize Template": "自定义模板",
  "Advanced Options": "高级选项",
  "Applying...": "应用中...",
  "Use Template": "使用模板",
  "editable fields": "个可编辑字段",
  "Audio Mixer": "音频混音器",
  "MASTER": "主输出",
  "Audio Mixing Console": "音频混音台",
  "Close mixer": "关闭混音器",
  "No audio tracks in timeline. Add audio or video tracks to see channel strips.": "时间线上还没有音频轨道。添加音频或视频轨道后即可查看通道条。",
  "Solo active": "独奏已启用",
  "Sample Rate:": "采样率：",
  "Channels:": "声道数：",
  "Volume fader": "音量推子",
  "Pan control": "声像控制",
  "Mute track": "静音轨道",
  "Unmute track": "取消静音轨道",
  "Solo track": "独奏轨道",
  "Unsolo track": "取消独奏轨道",
  "No selection": "未选择内容",
  "Select a clip to view its properties": "请选择一个片段以查看其属性",
  "Adjustment Layers": "调整图层",
  "Non-destructive effects on clips below": "对下方片段应用非破坏性效果",
  "Add Adjustment Layer": "添加调整图层",
  "Platform Presets": "平台预设",
  "Aspect Ratio": "宽高比",
  "Background Removal Ready": "背景移除已就绪",
  "Effect will be applied during playback": "效果将在播放时应用",
  "Processing Failed": "处理失败",
  "Could not enable background removal": "无法启用背景移除",
  "Background Removal Disabled": "背景移除已关闭",
  "Background Mode": "背景模式",
  "On": "开",
  "Off": "关",
  "Auto Reframe Applied": "智能重构图已应用",
  "Auto Reframe Failed": "智能重构图失败",
  "Finalizing...": "正在收尾...",
  "Complete": "完成",
  "Failed": "失败",
  "Waiting to start...": "等待开始...",
  "This shortcut conflicts with": "该快捷键与以下操作冲突：",
  "Choose a different key.": "请选择其他按键。",
  "Reset all shortcuts to defaults?": "要将所有快捷键重置为默认值吗？",
  "Applying a template will replace your current project. Continue?": "应用模板将替换当前项目，是否继续？",
  "M": "静音",
  "S": "独奏",
};

const REGEX_TRANSLATIONS: Array<[RegExp, (...args: string[]) => string]> = [
  [/^(\d+) days ago$/, (days) => `${days}天前`],
  [/^(\d+) weeks ago$/, (weeks) => `${weeks}周前`],
  [/^(\d+)h\s+(\d+)m remaining$/, (hours, minutes) => `剩余 ${hours}小时 ${minutes}分钟`],
  [/^(\d+)m remaining$/, (minutes) => `剩余 ${minutes}分钟`],
  [/^(\d+) key stored$/, (count) => `已存储 ${count} 个密钥`],
  [/^(\d+) keys stored$/, (count) => `已存储 ${count} 个密钥`],
  [/^Recent Projects \((\d+)\)$/, (count) => `最近项目（${count}）`],
  [/^(\d+) effects available$/, (count) => `共 ${count} 个可用效果`],
  [/^(\d+) recording imported!$/, (count) => `已导入 ${count} 个录制文件！`],
  [/^(\d+) recordings imported!$/, (count) => `已导入 ${count} 个录制文件！`],
  [/^Added (.+) · Updated (.+)$/, (created, updated) => `添加于 ${created} · 更新于 ${updated}`],
  [/^(\d+) older save available$/, (count) => `还有 ${count} 个较早的存档可恢复`],
  [/^(\d+) older saves available$/, (count) => `还有 ${count} 个较早的存档可恢复`],
  [/^(\d+) channel$/, (count) => `${count} 个通道`],
  [/^(\d+) channels$/, (count) => `${count} 个通道`],
  [/^(\d+)m ago$/, (minutes) => `${minutes}分钟前`],
  [/^(\d+)h ago$/, (hours) => `${hours}小时前`],
  [/^(\d+)d ago$/, (days) => `${days}天前`],
  [/^(\d+) editable fields$/, (count) => `${count} 个可编辑字段`],
  [/^Last saved (.+)$/, (when) => `最近保存于 ${when}`],
  [/^Theme:\s*light$/, () => "主题：浅色"],
  [/^Theme:\s*dark$/, () => "主题：深色"],
  [/^Theme:\s*system$/, () => "主题：跟随系统"],
  [/^Est\.\s*(.+)$/, (value) => `预计 ${value}`],
  [/^Max (\d+)s$/, (seconds) => `最长 ${seconds} 秒`],
  [/^(\d+) cores$/, (count) => `${count} 核`],
];

function preserveWhitespace(original: string, translated: string): string {
  const match = original.match(/^(\s*)(.*?)(\s*)$/s);
  if (!match) return translated;
  const [, leading, , trailing] = match;
  return `${leading}${translated}${trailing}`;
}

export function translateText(value: string): string {
  if (!value) return value;

  const trimmed = value.trim();
  if (!trimmed) return value;

  if (EXACT_TRANSLATIONS[trimmed]) {
    return preserveWhitespace(value, EXACT_TRANSLATIONS[trimmed]);
  }

  for (const [regex, replacer] of REGEX_TRANSLATIONS) {
    const match = trimmed.match(regex);
    if (match) {
      return preserveWhitespace(value, replacer(...match.slice(1)));
    }
  }

  return value;
}
